# Azure DevOps Pipeline for UserManagement solution
# Builds Web API + Blazor WASM, runs tests, deploys to Azure Web Apps

trigger:
  - main
  
pool:
    vmImage: 'windows-latest'
  
variables:
    solution: '**/*.sln'
    buildConfiguration: 'Release'
    buildPlatform: 'Any CPU'
    webAppName: 'UserManagement'          # Azure Web App name for API
    blazorAppName: 'BlazorApp'    # Azure Web App name for Blazor
  
steps:
  # Install .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  
  # Restore NuGet packages
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  
  # Build the solution
  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'
  
  # Run tests for all test projects
  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/*.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'
  
  # Publish Web API
  - task: DotNetCoreCLI@2
    displayName: 'Publish Web API'
    inputs:
      command: 'publish'
      projects: 'UserManagement.Web/UserManagement.Web.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/WebApp'
      zipAfterPublish: true
  
  # Publish Blazor WASM
  - task: DotNetCoreCLI@2
    displayName: 'Publish Blazor WASM'
    inputs:
      command: 'publish'
      projects: 'UserManagement.BlazorUI/UserManagement.BlazorUI.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/BlazorApp'
      zipAfterPublish: true
  
  # Deploy Web API to Azure
  - task: AzureWebApp@1
    displayName: 'Deploy Web API'
    inputs:
      azureSubscription: 'userconn'
      appType: 'webApp'
      appName: '$(webAppName)'
      package: '$(Build.ArtifactStagingDirectory)/WebApp.zip'
  
  # Deploy Blazor WASM to Azure
  - task: AzureWebApp@1
    displayName: 'Deploy Blazor WASM'
    inputs:
      azureSubscription: 'userconn'
      appType: 'webApp'
      appName: '$(blazorAppName)'
      package: '$(Build.ArtifactStagingDirectory)/BlazorApp.zip'
  