trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self

# Restore all projects
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: restore
    projects: '**/*.csproj'

# Build Web and Blazor
- task: DotNetCoreCLI@2
  displayName: 'Build Web'
  inputs:
    command: build
    projects: 'UserManagement.Web/UserManagement.Web.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build BlazorUI'
  inputs:
    command: build
    projects: 'UserManagement.BlazorUI/UserManagement.BlazorUI.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Publish artifacts
- task: DotNetCoreCLI@2
  displayName: 'Publish Web'
  inputs:
    command: publish
    projects: 'UserManagement.Web/UserManagement.Web.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Web'

- task: DotNetCoreCLI@2
  displayName: 'Publish BlazorUI'
  inputs:
    command: publish
    projects: 'UserManagement.BlazorUI/UserManagement.BlazorUI.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/BlazorUI'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
